from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from services.theme_templates import (
    DEFAULT_TEMPLATE_ID,
    TEMPLATES,
    ThemeTemplate,
    get_template_by_id,
)

BASE_DIR = Path(__file__).resolve().parent.parent
WEBAPP_DIR = BASE_DIR / "webapp"
THEME_CSS_PATH = WEBAPP_DIR / "css" / "theme.css"
THEME_BASE_PATH = WEBAPP_DIR / "css" / "theme.base.css"

DEFAULT_VARS: dict[str, str] = {
    "bg": "#f5f6fb",
    "text": "#1f2937",
    "muted": "#6b7280",
    "card-bg": "#ffffff",
    "accent": "#2563eb",
    "radius": "16px",
    "shadow": "0 16px 40px rgba(15, 23, 42, 0.12)",
    "font": '"Inter", system-ui, sans-serif',
}


class ThemeApplyError(RuntimeError):
    """Raised when theme file cannot be generated."""


def _normalize_template(template_id: str | None) -> ThemeTemplate:
    resolved = get_template_by_id(template_id)
    if resolved:
        return resolved
    fallback = get_template_by_id(DEFAULT_TEMPLATE_ID)
    if fallback:
        return fallback
    return TEMPLATES[0]


def _render_root_block(template: ThemeTemplate) -> str:
    css_vars = {**DEFAULT_VARS, **(template.css_vars or {})}
    card_border_color = (
        "rgba(0,0,0,0.08)"
        if (template.style_preset or {}).get("cardBorder")
        else "transparent"
    )

    lines: list[str] = ["/* Generated by AdminSite theme apply */", ":root {"]
    for key in ("bg", "text", "muted", "card-bg", "accent", "radius", "shadow", "font"):
        lines.append(f"  --{key}: {css_vars.get(key, '')};")
    lines.append(f"  --card-border-color: {card_border_color};")
    lines.append("")
    lines.extend(
        [
            "  --color-bg: var(--bg);",
            "  --color-bg-card: var(--card-bg);",
            "  --color-bg-card-elevated: var(--card-bg);",
            "  --color-text-main: var(--text);",
            "  --color-text-muted: var(--muted);",
            "  --color-border-subtle: var(--card-border-color);",
            "  --nav-surface: var(--card-bg);",
            "  --nav-border: var(--card-border-color);",
            "  --shadow-strong: var(--shadow);",
            "  --radius-card: var(--radius);",
            "  --radius-tile: calc(var(--radius) + 6px);",
            "  --radius-button: calc(var(--radius) - 4px);",
            "  --tile-gradient: linear-gradient(135deg, rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0));",
            "  --surface-primary: var(--card-bg);",
            "  --surface-secondary: var(--card-bg);",
            "  --color-accent-primary: var(--accent);",
            "  --color-accent-primary-strong: var(--accent);",
            "  --color-accent-secondary: var(--accent);",
            "  --color-accent-secondary-strong: var(--accent);",
            "  --color-accent-success: #3bb273;",
            "  --color-btn-on-accent: #0b0c10;",
        ]
    )
    lines.append("}")
    return "\n".join(lines)


def _build_theme_css(template_id: str | None) -> tuple[str, str]:
    template = _normalize_template(template_id)
    if not THEME_BASE_PATH.exists():
        raise ThemeApplyError("Base CSS file webapp/css/theme.base.css is missing")

    root_block = _render_root_block(template)
    base_css = THEME_BASE_PATH.read_text(encoding="utf-8")
    rendered_at = datetime.utcnow().isoformat()
    header = (
        f"/* template: {template.id} | generated_at: {rendered_at} */\n"
    )
    return template.id, "\n".join([header, root_block, "", base_css]).strip() + "\n"


def apply_theme(template_id: str | None) -> dict[str, Any]:
    template_key, content = _build_theme_css(template_id)
    try:
        THEME_CSS_PATH.parent.mkdir(parents=True, exist_ok=True)
        THEME_CSS_PATH.write_text(content, encoding="utf-8")
    except Exception as exc:  # pragma: no cover - filesystem errors
        raise ThemeApplyError(str(exc)) from exc

    updated_at = datetime.utcnow().isoformat()
    timestamp = int(THEME_CSS_PATH.stat().st_mtime)
    return {
        "appliedTemplateId": template_key,
        "timestamp": timestamp,
        "updatedAt": updated_at,
        "path": str(THEME_CSS_PATH),
    }


def parse_theme_metadata(text: str) -> dict[str, Any]:
    metadata: dict[str, Any] = {}
    if not text:
        return metadata

    first_line = text.splitlines()[0] if text else ""
    if "template:" in first_line:
        try:
            parts = {k.strip(): v.strip() for k, v in (segment.split(":", 1) for segment in first_line.strip("/* ").split("|"))}
            metadata["appliedTemplateId"] = parts.get("template")
            metadata["generatedAt"] = parts.get("generated_at") or parts.get("generatedAt")
        except Exception:
            pass
    return metadata


def get_theme_metadata() -> dict[str, Any]:
    if not THEME_CSS_PATH.exists():
        return {"appliedTemplateId": None, "timestamp": None, "updatedAt": None}

    try:
        content = THEME_CSS_PATH.read_text(encoding="utf-8")
    except Exception:
        content = ""

    metadata = parse_theme_metadata(content)
    timestamp = int(THEME_CSS_PATH.stat().st_mtime)
    updated_at = metadata.get("generatedAt") or datetime.utcfromtimestamp(timestamp).isoformat()

    return {
        "appliedTemplateId": metadata.get("appliedTemplateId") or None,
        "timestamp": timestamp,
        "updatedAt": updated_at,
    }


__all__ = [
    "apply_theme",
    "get_theme_metadata",
    "DEFAULT_TEMPLATE_ID",
    "THEME_BASE_PATH",
    "THEME_CSS_PATH",
    "ThemeApplyError",
]
